/* DO NOT EDIT THIS FILE - it is machine generated */
#include "include/jni.h"
/* Header for class Test2_Tester */

#ifndef _Included_Test2_Tester
#define _Included_Test2_Tester
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     Test2_Tester
	 * Method:    initObject
	 * Signature: ()LTest2/Person;
	 */
	JNIEXPORT jobject JNICALL Java_Test2_Tester_initObject
	(JNIEnv*, jobject);

	/*
	 * Class:     Test2_Tester
	 * Method:    printObjects
	 * Signature: ([LTest2/Person;)V
	 */
	JNIEXPORT void JNICALL Java_Test2_Tester_printObjects
	(JNIEnv*, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
